version: '3'
services:
  gotenberg:
    container_name: gotenberg
    build: ./gotenberg/
    ports:
      - 8000:3000
  
  backend-dotnet:
    container_name: backend-dotnet
    build: ./dotnet/
    ports:
      - 5000:8080

  frontend-node-react-pdf:
    container_name: frontend-node-react-pdf
    build: ./frontend-react/
    ports:
      - 4200:4200