version: '3'
services:
  gotenberg:
    build: ./gotenberg/
    ports:
      - 8000:3000
  
  backend-dotnet:
    build: ./dotnet/
    ports:
      - 5000:8080

  frontend-node-react:
    build: ./frontend-react/
    ports:
      - 4200:4200