apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg-deployment
  namespace: dotnet-gotenberg-node-react-pdf-k8s
  labels:
    app: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotenberg
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
      - name: gotenberg
        image: liminha/gotenberg:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg-service
  namespace: dotnet-gotenberg-node-react-pdf-k8s
spec:
  type: LoadBalancer
  selector:
    app: gotenberg
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
