name: Frontend React

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        cd frontend-react && npm install

    - name: Build Project
      run: |
        cd frontend-react && npm install

    - name: LS
      run: |
        ls

    - name: PWS
      run: |
        pwd

    - name: Publish Pipeline Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./frontend-react/build
        
  Deploy_DSV:
    needs: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        echo "deploy on dsv"

        
